spring:
  mvc.view:
    prefix:  /WEB-INF/views/
    suffix: .jsp
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospitalmanagement?useSSL=false
    username: root
